# Build speed
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.daemon.jvmargs=-Xmx2g
# Gradle 8.11 runs on JDK 17/21.
org.gradle.java.home=C:/Users/sdroy/.gradle/jdks/eclipse_adoptium-17-amd64-windows.2

android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
kotlin.code.style=official
